version: '2'

services:
  ca.ibm.platform-configuration.com:
    image: hyperledger/fabric-ca:1.2.1
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.ibm.platform-configuration.com

    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.ibm.platform-configuration.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/f1829c5c9e9037b96f67896b7035abf0d58ab549f53d6d6748f401844db57ea1_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/ibm.platform-configuration.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca.ibm.platform-configuration.com

  orderer.platform-configuration.com:
    container_name: orderer.platform-configuration.com
    image: hyperledger/fabric-orderer:1.2.1
    environment:
      - ORDERER_GENERAL_LOGLEVEL=debug
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/etc/hyperledger/configtx/composer-genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/msp/orderer/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    ports:
      - 7050:7050
    volumes:
        - ./:/etc/hyperledger/configtx
        - ./crypto-config/ordererOrganizations/platform-configuration.com/orderers/orderer.platform-configuration.com/msp:/etc/hyperledger/msp/orderer/msp

  peer0.ibm.platform-configuration.com:
    container_name: peer0.ibm.platform-configuration.com
    image: hyperledger/fabric-peer:1.2.1
    environment:
      - CORE_LOGGING_LEVEL=debug
      - CORE_CHAINCODE_LOGGING_LEVEL=DEBUG
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer0.ibm.platform-configuration.com
      - CORE_PEER_ADDRESS=peer0.ibm.platform-configuration.com:7051
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=composer_default
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/peer/msp
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb:5984
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: peer node start
    ports:
      - 7051:7051
      - 7053:7053
    volumes:
        - /var/run/:/host/var/run/
        - ./:/etc/hyperledger/configtx
        - ./crypto-config/peerOrganizations/ibm.platform-configuration.com/peers/peer0.ibm.platform-configuration.com/msp:/etc/hyperledger/peer/msp
        - ./crypto-config/peerOrganizations/ibm.platform-configuration.com/users:/etc/hyperledger/msp/users
    depends_on:
      - orderer.platform-configuration.com
      - couchdb

  couchdb:
    container_name: couchdb
    image: hyperledger/fabric-couchdb:0.4.10
    ports:
      - 5984:5984
    environment:
      DB_URL: http://localhost:5984/member_db
